[project]
name = "usstziyi-musical-happiness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "007", email = "007lookworld@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openpyxl>=3.1.5",
    "torch>=2.13.0",
    "transformers>=5.16.1",
]

